apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-create-signed-cert-validation-webhook
data:
  create_webhook_from_configmap.sh: |
        #!/usr/bin/env bash
        set -ex
        export CABUNDLE=$(cat /etc/nexus-validation/tls/ca.crt | base64 - | tr -d '\n')
        usage() {
            cat <<EOF

        usage: ${0} [OPTIONS]

        The following flags are required.

                --server apiserver to connect and create webhook.

        EOF
            exit 1
        }
        while [[ $# -gt 0 ]]; do
            case ${1} in
                --server)
                    server="$2"
                    shift
                    ;;
                *)
                    usage
                    ;;
            esac
            shift
        done
        sed -e "s|__CA_BUNDLE__|${CABUNDLE}|g" /etc/validation-webhook/config | kubectl -s $server apply -f -

  create_certificate_as_secret.sh: |
        #!/usr/bin/env bash
        set -ex
        namespace=$POD_NAMESPACE
        usage() {
            cat <<EOF
        Generate certificate suitable for use with an webhook service.

        This script uses k8s' CertificateSigningRequest API to a generate a
        certificate signed by k8s CA suitable for use with sidecar-injector webhook
        services. This requires permissions to create and approve CSR. See
        https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster for
        detailed explantion and additional instructions.

        The server key/cert k8s CA cert are stored in a k8s secret.

        usage: ${0} [OPTIONS]

        The following flags are required.

                --service          Service name of webhook.
                --namespace        Namespace where webhook service and secret reside.
                --secret           Secret name for CA certificate and server certificate/key pair.
        EOF
            exit 1
        }

        while [[ $# -gt 0 ]]; do
            case ${1} in
                --service)
                    service="$2"
                    shift
                    ;;
                --secret)
                    secret="$2"
                    shift
                    ;;
                *)
                    usage
                    ;;
            esac
            shift
        done

        if [ ! -x "$(command -v openssl)" ]; then
            echo "openssl not found"
            exit 1
        fi

        csrName=${service}
        tmpdir=$(mktemp -d)
        echo "creating certs in tmpdir ${tmpdir} "

        cat <<EOF >> ${tmpdir}/csr.conf
        [req]
        req_extensions = v3_req
        distinguished_name = req_distinguished_name
        [req_distinguished_name]
        [ v3_req ]
        basicConstraints = CA:FALSE
        keyUsage = digitalSignature, keyEncipherment
        extendedKeyUsage = serverAuth
        subjectAltName = @alt_names
        [alt_names]
        DNS.1 = ${service}
        DNS.2 = ${service}.${namespace}
        DNS.3 = ${service}.${namespace}.svc
        DNS.4 = localhost
        EOF

        openssl genrsa -out ${tmpdir}/server-key.pem 2048
        openssl req -new -x509 -nodes -days 365000 -key  ${tmpdir}/server-key.pem -out ${tmpdir}/ca-cert.pem -subj "/C=US/ST=Denial/L=PaloAlto/O=Dis/CN=nexus"
        openssl req -new -key ${tmpdir}/server-key.pem -subj "/CN=${service}" -out ${tmpdir}/server.csr -config ${tmpdir}/csr.conf
        openssl x509 -req -days 365 -in ${tmpdir}/server.csr -CAcreateserial -signkey ${tmpdir}/server-key.pem -sha256 -out ${tmpdir}/server.crt -CA ${tmpdir}/ca-cert.pem -CAkey ${tmpdir}/server-key.pem
        openssl x509 -in ${tmpdir}/server.crt -out ${tmpdir}/server-cert.pem -outform PEM

        # create the secret with CA cert and server cert/key
        kubectl create secret generic ${secret} \
                --from-file=tls.key=${tmpdir}/server-key.pem \
                --from-file=tls.crt=${tmpdir}/server-cert.pem \
                --from-file=ca.crt=${tmpdir}/ca-cert.pem \
                --dry-run -o yaml |
            kubectl -n ${namespace} apply -f -
---
apiVersion: batch/v1
kind: Job
metadata:
  name: nexus-create-signed-cert-validation-webhook
  annotations:
    "nexus-upgrade": "false"
spec:
  backoffLimit: 6
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      containers:
        - command:
            - /opt/create_webhook_signed_cert/create_certificate_as_secret.sh
            - --service
            - nexus-validation
            - --secret
            - nexus-validation-tls
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: "gcr.io/nsx-sm/bitnami/kubectl:1.16"
          imagePullPolicy: IfNotPresent
          name: nexus-create-signed-cert-validation-webhook
          volumeMounts:
            - mountPath: /opt/create_webhook_signed_cert/
              name: nexus-create-signed-cert-validation-webhook
              readOnly: false
      restartPolicy: Never
      serviceAccountName: nexus-k8scerts-service-account
      volumes:
        - configMap:
            name: nexus-create-signed-cert-validation-webhook
            defaultMode: 0555
          name: nexus-create-signed-cert-validation-webhook
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-webhook-config
data:
  config: |
      apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      metadata:
        name: "nexus-validation.webhook.svc"
      webhooks:
        - name: "nexus-validation-crd.webhook.svc"
          failurePolicy: Ignore
          rules:
            - apiGroups: [ "" ]
              apiVersions: [ "v1" ]
              operations: [ "CREATE" ]
              resources: [ "*" ]
              scope: "*"
          clientConfig:
            url: https://nexus-validation/validate
            caBundle: __CA_BUNDLE__
          admissionReviewVersions: [ "v1", "v1beta1" ]
          sideEffects: None
        - name: "nexus-validation-crd-type.webhook.svc"
          failurePolicy: Ignore
          rules:
            - apiGroups: [ "apiextensions.k8s.io" ]
              apiVersions: [ "v1" ]
              operations: [ "CREATE", "UPDATE" ]
              resources: [ "customresourcedefinitions" ]
              scope: "Cluster"
          clientConfig:
            url: https://nexus-validation/validate-crd-type
            caBundle: __CA_BUNDLE__
          admissionReviewVersions: [ "v1", "v1beta1" ]
          sideEffects: None
---
apiVersion: batch/v1
kind: Job
metadata:
  name: nexus-validation-webhook-creation
  annotations:
    "nexus-upgrade": "false"
spec:
  backoffLimit: 6
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      initContainers:
        - name: check-nexus-proxy-container
          image: "gcr.io/nsx-sm/tools:latest"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              set -x
              URL="http://nexus-proxy-container/api/v1/namespaces"
              max_retries=20
              counter=0
              while [[ $counter -lt $max_retries ]]; do
                    status=$(curl -s -o /dev/null -I -w "%{http_code}" -XGET $URL)
                    if [ $status == "200" ]; then
                        echo "$URL is reachable"
                        exit 0
                    else
                        counter=$((counter +1))
                        sleep 5
                        if [[ $counter -eq $max_retries ]]; then
                            exit 1
                        fi
                    fi
              done
      containers:
        - command:
            - /opt/create_webhook_signed_cert/create_webhook_from_configmap.sh
            - --server
            - nexus-proxy-container
          image: "gcr.io/nsx-sm/bitnami/kubectl:1.16"
          imagePullPolicy: IfNotPresent
          name: nexus-create-signed-cert-validation-webhook
          volumeMounts:
            - mountPath: /opt/create_webhook_signed_cert/
              name: nexus-create-signed-cert-validation-webhook
              readOnly: false
            - mountPath: /etc/validation-webhook
              name: nexus-webhook-config
              readOnly: false
            - name: tls
              mountPath: "/etc/nexus-validation/tls"
              readOnly: true
      restartPolicy: OnFailure
      serviceAccountName: nexus-k8scerts-service-account
      volumes:
        - configMap:
            name: nexus-create-signed-cert-validation-webhook
            defaultMode: 0555
          name: nexus-create-signed-cert-validation-webhook
        - configMap:
            name: nexus-webhook-config
            defaultMode: 0555
          name: nexus-webhook-config
        - name: tls
          secret:
            secretName: nexus-validation-tls
